# Generated by Django 4.2 on 2024-03-20 13:09

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True, verbose_name="опубликовано"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150, verbose_name="название"),
                ),
                (
                    "text",
                    models.TextField(
                        validators=[catalog.models.perfect_validator],
                        verbose_name="текст",
                    ),
                ),
            ],
        ),
    ]
